# Pycaret modeling

In [1]:
import pandas as pd
from pycaret.regression import *

In [2]:
players_stats = pd.read_csv('data/players_stats.csv' ,sep=';')

In [3]:
players_stats

,id,player,player_team,s1,opponent,s2,rating2.0,map,date,event_type,event_tier,team_rank,opponent_rank,rank_difference,favorite,round_difference,win,team_rating
0,11893,zywoo,Vitality,10,AVANGAR,16,1.04,d2,2019-05-09,major,S,11.0,14.0,-3.0,True,-6,False,0.6975
1,11893,zywoo,Vitality,16,AVANGAR,11,1.63,inf,2019-05-09,major,S,11.0,14.0,-3.0,True,5,True,1.0625
2,11893,zywoo,Vitality,9,AVANGAR,16,0.90,mrg,2019-05-09,major,S,11.0,14.0,-3.0,True,-7,False,0.9075
3,11893,zywoo,Vitality,16,MOUZ,10,1.52,mrg,2019-08-31,major,S,2.0,9.0,-7.0,True,6,True,1.1700
4,11893,zywoo,Vitality,16,MOUZ,5,1.44,vtg,2019-08-31,major,S,2.0,9.0,-7.0,True,11,True,1.3250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42981,13461,wannafly,Lucid Dream,16,NASR,1,1.17,d2,2019-03-22,online,B,35.0,35.0,0.0,False,15,True,1.7950
42982,13461,wannafly,Lucid Dream,16,NASR,9,1.60,nuke,2019-03-22,online,B,35.0,35.0,0.0,False,7,True,1.1650
42983,13461,wannafly,Lucid Dream,8,NASR,16,0.79,ovp,2019-03-22,online,B,35.0,35.0,0.0,False,-8,False,0.7775
42984,13461,wannafly,Lucid Dream,16,Entity,1,1.23,mrg,2019-03-22,online,B,35.0,35.0,0.0,False,15,True,1.6500
42985,13461,wannafly,Lucid Dream,16,Entity,5,1.54,nuke,2019-03-22,online,B,35.0,35.0,0.0,False,11,True,1.4900

In [5]:
#players_stats.drop(['date','opponent','player','player_team'],axis = 1,inplace = True)

In [4]:
players_stats = players_stats.astype({'id':str})

In [5]:
players_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42986 entries, 0 to 42985
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                42986 non-null  object
 1   player            42986 non-null  object
 2   player_team       42986 non-null  object
 3   s1                42986 non-null  int64
 4   opponent          42986 non-null  object
 5   s2                42986 non-null  int64
 6   rating2.0         42986 non-null  float64
 7   map               42986 non-null  object
 8   date              42986 non-null  object
 9   event_type        42986 non-null  object
 10  event_tier        42986 non-null  object
 11  team_rank         42986 non-null  float64
 12  opponent_rank     42986 non-null  float64
 13  rank_difference   42986 non-null  float64
 14  favorite          42986 non-null  bool
 15  round_difference  42986 non-null  int64
 16  win               42986 non-null  bool
 17  team_rating       42986 non-null  float64
dtypes: bool(2), float64(5), int64(3), object(8)
memory usage: 5.3+ MB

# General model

In [8]:
model = setup(data = players_stats.drop(['id','date','player','opponent'],axis=1),target='rating2.0',session_id=42,normalize=True)

In [9]:
best = compare_models()

In [10]:
evaluate_model(best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'paramâ€¦

In [9]:
save_model(best,'rating_pred')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=True, features_todrop=[],
                                       id_columns=[], ml_usecase='regression',
                                       numerical_features=[], target='rating2.0',
                                       time_features=[])),
                 ('imputer',
                  Simple_Imputer(categorical_strategy='not_available',
                                 fill_value_categorical=None,
                                 fill_value_numerical=None,
                                 numeric_strate...
                  ExtraTreesRegressor(bootstrap=False, ccp_alpha=0.0,
                                      criterion='mse', max_depth=None,
                                      max_features='auto', max_leaf_nodes=None,
                                      max_samples=None,
                                      min_impurity_decrease=0.0,
                                      min_impurity_split=None,
                                      min_samples_leaf=1, min_samples_split=2,
                                      min_weight_fraction_leaf=0.0,
                                      n_estimators=100, n_jobs=-1,
                                      oob_score=False, random_state=42,
                                      verbose=0, warm_start=False)]],
          verbose=False),
 'rating_pred.pkl')